ci:
  autofix_prs: true
  autoupdate_schedule: monthly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-json
    exclude: |
      (?x)^(
        \.vscode/.*\.json
      )$
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.37.4
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.6
  hooks:
  - id: insert-license
    files: \.py$
    args:
    - --license-filepath=license_header.txt
    - --use-current-year

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.1
  hooks:
  - id: ruff-check
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.3.0
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests
    exclude: tests/
